"""Generate the K.6 test file correctly."""
import pathlib

p = pathlib.Path("tests/unit/test_k6_command.py")
with p.open("w", encoding="utf-8") as f:
    f.write('"""FASE K.6 - Unit tests for secure command execution."""\n\n')
    f.write('from pathlib import Path\n')
    f.write('from unittest.mock import AsyncMock\n\n')
    f.write('import pytest\n\n')
    f.write('from personal_ai_secretary.tools.command import (\n')
    f.write('    ALLOWED_EXECUTABLES,\n')
    f.write('    BLOCKED_EXECUTABLES,\n')
    f.write('    _extract_executable_name,\n')
    f.write('    _has_chaining,\n')
    f.write('    _has_path_traversal,\n')
    f.write('    _truncate_output,\n')
    f.write('    _execute_command,\n')
    f.write('    register_command_tools,\n')
    f.write('    validate_command,\n')
    f.write('    validate_working_directory,\n')
    f.write('    _MAX_STDOUT_CHARS,\n')
    f.write(')\n')
    f.write('from personal_ai_secretary.tools.registry import ToolError, ToolRegistry, ToolRisk\n\n\n')

    # TestAllowlist
    f.write('class TestAllowlist:\n')
    f.write('    def test_allowed_executables_present(self) -> None:\n')
    f.write('        for name in ("python", "pytest", "node", "git", "where"):\n')
    f.write('            assert name in ALLOWED_EXECUTABLES\n\n')
    f.write('    def test_blocked_executables_present(self) -> None:\n')
    f.write('        for name in ("powershell", "cmd", "shutdown", "del", "rmdir", "diskpart", "net", "sc"):\n')
    f.write('            assert name in BLOCKED_EXECUTABLES\n\n')
    f.write('    def test_disjoint(self) -> None:\n')
    f.write('        assert ALLOWED_EXECUTABLES.isdisjoint(BLOCKED_EXECUTABLES)\n\n\n')

    # TestExtractExecutableName
    f.write('class TestExtractExecutableName:\n')
    f.write('    def test_bare_name(self) -> None:\n')
    f.write('        assert _extract_executable_name("python --version") == "python"\n\n')
    f.write('    def test_full_path_windows(self) -> None:\n')
    f.write('        assert _extract_executable_name(r"C:\\Python313\\python.exe --version") == "python"\n\n')
    f.write('    def test_extension_stripped(self) -> None:\n')
    f.write('        assert _extract_executable_name("git.exe status") == "git"\n')
    f.write('        assert _extract_executable_name("npm.cmd install") == "npm"\n\n')
    f.write('    def test_empty(self) -> None:\n')
    f.write('        assert _extract_executable_name("") == ""\n')
    f.write('        assert _extract_executable_name("   ") == ""\n\n')
    f.write('    def test_case_insensitive(self) -> None:\n')
    f.write('        assert _extract_executable_name("PYTHON --version") == "python"\n\n\n')

    # TestChainingDetection
    f.write('class TestChainingDetection:\n')
    f.write('    def test_simple_commands(self) -> None:\n')
    f.write('        for cmd in ("python --version", "pytest tests/", "git status"):\n')
    f.write('            assert not _has_chaining(cmd)\n\n')
    f.write('    def test_double_ampersand(self) -> None:\n')
    f.write('        assert _has_chaining("python --version && pytest")\n\n')
    f.write('    def test_double_pipe(self) -> None:\n')
    f.write('        assert _has_chaining("python script.py || echo failed")\n\n')
    f.write('    def test_single_pipe(self) -> None:\n')
    f.write('        assert _has_chaining("dir | findstr .py")\n\n')
    f.write('    def test_semicolon(self) -> None:\n')
    f.write('        assert _has_chaining("python --version; pytest")\n\n')
    f.write('    def test_redirect(self) -> None:\n')
    f.write('        assert _has_chaining("dir > output.txt")\n')
    f.write('        assert _has_chaining("echo test >> log.txt")\n')
    f.write('        assert _has_chaining("type < input.txt")\n\n')
    f.write('    def test_backtick(self) -> None:\n')
    f.write('        assert _has_chaining("`whoami`")\n\n')
    f.write('    def test_dollar_paren(self) -> None:\n')
    f.write('        assert _has_chaining("$(whoami)")\n\n')
    f.write('    def test_dollar_brace(self) -> None:\n')
    f.write('        assert _has_chaining("echo ${HOME}")\n\n')
    f.write('    def test_malformed_quotes(self) -> None:\n')
    f.write('        assert _has_chaining(\'echo "unclosed\')\n\n\n')

    # TestPathTraversalDetection
    f.write('class TestPathTraversalDetection:\n')
    f.write('    def test_no_traversal(self) -> None:\n')
    f.write('        assert not _has_path_traversal("python script.py")\n')
    f.write('        assert not _has_path_traversal("pytest tests/test_foo.py")\n\n')
    f.write('    def test_dot_dot_in_arg(self) -> None:\n')
    f.write('        assert _has_path_traversal("python ../escape.py")\n')
    f.write('        assert _has_path_traversal("type ../../etc/passwd")\n\n')
    f.write('    def test_dot_dot_not_in_executable(self) -> None:\n')
    f.write('        assert not _has_path_traversal("python --version")\n\n\n')

    # TestValidateCommand
    f.write('class TestValidateCommand:\n')
    f.write('    def test_valid_simple(self) -> None:\n')
    f.write('        assert validate_command("python --version") == "python --version"\n\n')
    f.write('    def test_valid_pytest(self) -> None:\n')
    f.write('        assert validate_command("pytest tests/") == "pytest tests/"\n\n')
    f.write('    def test_valid_git(self) -> None:\n')
    f.write('        assert validate_command("git status") == "git status"\n\n')
    f.write('    def test_empty_raises(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="Empty command"):\n')
    f.write('            validate_command("")\n\n')
    f.write('    def test_whitespace_only_raises(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="Empty command"):\n')
    f.write('            validate_command("   ")\n\n')
    f.write('    def test_chaining_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="chaining"):\n')
    f.write('            validate_command("python && pytest")\n\n')
    f.write('    def test_pipe_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="chaining"):\n')
    f.write('            validate_command("dir | findstr .py")\n\n')
    f.write('    def test_semicolon_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="chaining"):\n')
    f.write('            validate_command("python; pytest")\n\n')
    f.write('    def test_redirect_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="chaining"):\n')
    f.write('            validate_command("dir > output.txt")\n\n')
    f.write('    def test_backtick_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="chaining"):\n')
    f.write('            validate_command("`whoami`")\n\n')
    f.write('    def test_dollar_paren_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="chaining"):\n')
    f.write('            validate_command("$(whoami)")\n\n')
    f.write('    def test_path_traversal_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="path traversal"):\n')
    f.write('            validate_command("python ../escape.py")\n\n')
    f.write('    def test_powershell_blocked(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="blocked"):\n')
    f.write('            validate_command("powershell -Command Get-Date")\n\n')
    f.write('    def test_cmd_blocked(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="blocked"):\n')
    f.write('            validate_command("cmd /c dir")\n\n')
    f.write('    def test_shutdown_blocked(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="blocked"):\n')
    f.write('            validate_command("shutdown /s /t 0")\n\n')
    f.write('    def test_unlisted_rejected(self) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="not in the allowlist"):\n')
    f.write('            validate_command("curl http://example.com")\n\n')
    f.write('    def test_strip_whitespace(self) -> None:\n')
    f.write('        assert validate_command("  python --version  ") == "python --version"\n\n')
    f.write('    def test_full_path_allowed(self) -> None:\n')
    f.write('        result = validate_command(r"C:\\Python313\\python.exe --version")\n')
    f.write('        assert result == r"C:\\Python313\\python.exe --version"\n\n\n')

    # TestValidateWorkingDirectory
    f.write('class TestValidateWorkingDirectory:\n')
    f.write('    def test_none_returns_cwd(self) -> None:\n')
    f.write('        result = validate_working_directory(None)\n')
    f.write('        assert result == str(Path.cwd())\n\n')
    f.write('    def test_empty_returns_cwd(self) -> None:\n')
    f.write('        result = validate_working_directory("")\n')
    f.write('        assert result == str(Path.cwd())\n\n')
    f.write('    def test_existing_directory(self, tmp_path: Path) -> None:\n')
    f.write('        result = validate_working_directory(str(tmp_path))\n')
    f.write('        assert result == str(tmp_path)\n\n')
    f.write('    def test_nonexistent_directory(self, tmp_path: Path) -> None:\n')
    f.write('        fake = tmp_path / "nonexistent"\n')
    f.write('        with pytest.raises(ToolError, match="does not exist"):\n')
    f.write('            validate_working_directory(str(fake))\n\n')
    f.write('    def test_file_not_directory(self, tmp_path: Path) -> None:\n')
    f.write('        f = tmp_path / "file.txt"\n')
    f.write('        f.write_text("data")\n')
    f.write('        with pytest.raises(ToolError, match="not a directory"):\n')
    f.write('            validate_working_directory(str(f))\n\n')
    f.write('    def test_outside_allowed_roots(self, tmp_path: Path) -> None:\n')
    f.write('        with pytest.raises(ToolError, match="outside allowed"):\n')
    f.write('            validate_working_directory(str(tmp_path), allowed_roots=["C:\\\\Users\\\\other"])\n\n')
    f.write('    def test_within_allowed_roots(self, tmp_path: Path) -> None:\n')
    f.write('        result = validate_working_directory(str(tmp_path), allowed_roots=[str(tmp_path.parent)])\n')
    f.write('        assert result == str(tmp_path)\n\n\n')

    # TestTruncateOutput
    f.write('class TestTruncateOutput:\n')
    f.write('    def test_short_not_truncated(self) -> None:\n')
    f.write('        text, truncated = _truncate_output("hello", 100)\n')
    f.write('        assert text == "hello"\n')
    f.write('        assert not truncated\n\n')
    f.write('    def test_exact_limit(self) -> None:\n')
    f.write('        _, truncated = _truncate_output("x" * 100, 100)\n')
    f.write('        assert not truncated\n\n')
    f.write('    def test_long_truncated(self) -> None:\n')
    f.write('        result, truncated = _truncate_output("x" * 10_000, 1000)\n')
    f.write('        assert truncated\n')
    f.write('        assert len(result) <= 1200\n')
    f.write('        assert "truncated" in result.lower()\n\n')
    f.write('    def test_head_tail_preserved(self) -> None:\n')
    f.write('        text = "HEAD" + "M" * 1000 + "TAIL"\n')
    f.write('        result, truncated = _truncate_output(text, 200)\n')
    f.write('        assert truncated\n')
    f.write('        assert result.startswith("HEAD")\n')
    f.write('        assert result.endswith("TAIL")\n\n\n')

    # TestExecuteCommand
    f.write('class TestExecuteCommand:\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_empty_command(self) -> None:\n')
    f.write('        result = await _execute_command({"command": ""})\n')
    f.write('        assert "error" in result\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_blocked_command(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "powershell -Command Get-Date"})\n')
    f.write('        assert "error" in result\n')
    f.write('        assert "blocked" in result["error"].lower()\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_chaining_rejected(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python && pytest"})\n')
    f.write('        assert "error" in result\n')
    f.write('        assert "chaining" in result["error"].lower()\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_unlisted_executable(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "curl http://example.com"})\n')
    f.write('        assert "error" in result\n')
    f.write('        assert "not in the allowlist" in result["error"]\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_python_success(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"print(42)\\""})\n')
    f.write('        assert result.get("success") is True\n')
    f.write('        assert result["exit_code"] == 0\n')
    f.write('        assert "42" in result["stdout"]\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_nonexistent_working_dir(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"print(1)\\"", "working_directory": "Z:\\\\nonexistent"})\n')
    f.write('        assert "error" in result\n')
    f.write('        assert "does not exist" in result["error"]\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_exit_code_nonzero(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"import sys; sys.exit(42)\\""})\n')
    f.write('        assert result.get("success") is False\n')
    f.write('        assert result["exit_code"] == 42\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_output_truncation(self, tmp_path: Path) -> None:\n')
    f.write('        script = tmp_path / "big.py"\n')
    f.write('        script.write_text(\'print("x" * 50000)\')\n')
    f.write('        result = await _execute_command({"command": f"python {script}", "working_directory": str(tmp_path)})\n')
    f.write('        assert result.get("success") is True\n')
    f.write('        assert result.get("output_truncated") is True\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_stderr_captured(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"import sys; sys.stderr.write(chr(10).join([chr(101)+chr(114)+chr(114)+chr(95)+chr(109)+chr(115)+chr(103)])); sys.exit(1)\\""})\n')
    f.write('        assert result.get("success") is False\n')
    f.write('        assert "err_msg" in result["stderr"]\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_working_directory_used(self, tmp_path: Path) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"import os; print(os.getcwd())\\"", "working_directory": str(tmp_path)})\n')
    f.write('        assert result.get("success") is True\n')
    f.write('        assert result["working_directory"] == str(tmp_path)\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_duration_recorded(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"print(1)\\""})\n')
    f.write('        assert result["duration"] >= 0.0\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_path_traversal_rejected(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python ../escape.py"})\n')
    f.write('        assert "error" in result\n')
    f.write('        assert "path traversal" in result["error"].lower()\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_timeout_exceeded(self, tmp_path: Path) -> None:\n')
    f.write('        script = tmp_path / "slow.py"\n')
    f.write('        script.write_text("import time; time.sleep(10)")\n')
    f.write('        result = await _execute_command({"command": f"python {script}", "working_directory": str(tmp_path), "timeout": 1})\n')
    f.write('        assert result.get("success") is False\n')
    f.write('        assert result.get("timeout") is True\n')
    f.write('        assert result["exit_code"] == -1\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_result_structure(self) -> None:\n')
    f.write('        result = await _execute_command({"command": "python -c \\"print(1)\\""})\n')
    f.write('        for key in ("success", "exit_code", "stdout", "stderr", "duration", "working_directory"):\n')
    f.write('            assert key in result\n\n\n')

    # TestToolRegistryIntegration
    f.write('class TestToolRegistryIntegration:\n')
    f.write('    def test_register(self) -> None:\n')
    f.write('        registry = ToolRegistry()\n')
    f.write('        register_command_tools(registry)\n')
    f.write('        defn = registry.get("execute_command")\n')
    f.write('        assert defn is not None\n')
    f.write('        assert defn.risk == ToolRisk.HIGH\n')
    f.write('        assert defn.requires_explicit_approval is True\n')
    f.write('        assert "working_directory" in defn.optional_arguments\n')
    f.write('        assert "timeout" in defn.optional_arguments\n\n')
    f.write('    def test_compact_description(self) -> None:\n')
    f.write('        registry = ToolRegistry()\n')
    f.write('        register_command_tools(registry)\n')
    f.write('        descs = registry.compact_descriptions()\n')
    f.write('        assert any("execute_command" in d for d in descs)\n\n')
    f.write('    def test_in_default_registry(self) -> None:\n')
    f.write('        from personal_ai_secretary.tools.builtin import default_tool_registry\n')
    f.write('        assert "execute_command" in default_tool_registry().names()\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_requires_approval(self) -> None:\n')
    f.write('        from personal_ai_secretary.tools.builtin import default_tool_registry\n')
    f.write('        registry = default_tool_registry()\n')
    f.write('        with pytest.raises(PermissionError):\n')
    f.write('            await registry.execute("execute_command", {"command": "python -c \\"print(1)\\""}, approved=False)\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_approved_execution(self) -> None:\n')
    f.write('        from personal_ai_secretary.tools.builtin import default_tool_registry\n')
    f.write('        registry = default_tool_registry()\n')
    f.write('        result = await registry.execute("execute_command", {"command": "python -c \\"print(1)\\""}, approved=True)\n')
    f.write('        assert result.get("success") is True\n\n\n')

    # TestRequestMetricsK6
    f.write('class TestRequestMetricsK6:\n')
    f.write('    def test_defaults(self) -> None:\n')
    f.write('        from personal_ai_secretary.observability.request_metrics import RequestMetrics\n')
    f.write('        m = RequestMetrics()\n')
    f.write('        assert m.command_count == 0\n')
    f.write('        assert m.command_timeout_count == 0\n')
    f.write('        assert m.command_output_chars == 0\n\n')
    f.write('    def test_record_command(self) -> None:\n')
    f.write('        from personal_ai_secretary.observability.request_metrics import RequestMetrics\n')
    f.write('        m = RequestMetrics()\n')
    f.write('        m.record_command(duration=1.5, exit_code=0, output_chars=500)\n')
    f.write('        assert m.command_count == 1\n')
    f.write('        assert m.command_durations == [1.5]\n\n')
    f.write('    def test_record_timeout(self) -> None:\n')
    f.write('        from personal_ai_secretary.observability.request_metrics import RequestMetrics\n')
    f.write('        m = RequestMetrics()\n')
    f.write('        m.record_command(duration=30.0, exit_code=-1, timed_out=True)\n')
    f.write('        assert m.command_timeout_count == 1\n\n')
    f.write('    def test_summary_keys(self) -> None:\n')
    f.write('        from personal_ai_secretary.observability.request_metrics import RequestMetrics\n')
    f.write('        m = RequestMetrics()\n')
    f.write('        m.record_command(duration=1.0, exit_code=0)\n')
    f.write('        s = m.summary()\n')
    f.write('        assert "command_count" in s\n')
    f.write('        assert "command_avg_duration_s" in s\n')
    f.write('        assert s["command_count"] == 1\n\n\n')

    # TestPromptIntegration
    f.write('class TestPromptIntegration:\n')
    f.write('    def test_command_in_prompt(self) -> None:\n')
    f.write('        from personal_ai_secretary.tools.prompt import build_system_prompt\n')
    f.write('        prompt = build_system_prompt(tool_names=["execute_command", "read_file"], compact_descriptions=["execute_command: Execute safe shell command"])\n')
    f.write('        assert "Command Execution" in prompt\n\n')
    f.write('    def test_not_in_prompt_without_tool(self) -> None:\n')
    f.write('        from personal_ai_secretary.tools.prompt import build_system_prompt\n')
    f.write('        prompt = build_system_prompt(tool_names=["read_file"], compact_descriptions=["read_file: Read a file"])\n')
    f.write('        assert "Command Execution" not in prompt\n\n\n')

    # TestExecutionAgentK6
    f.write('class TestExecutionAgentK6:\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_approval_required(self) -> None:\n')
    f.write('        from personal_ai_secretary.agents.builtin import ExecutionAgent, APPROVAL_REQUIRED_PREFIX\n')
    f.write('        from personal_ai_secretary.agents.contracts import AgentInput\n')
    f.write('        from personal_ai_secretary.domain.contracts import ProviderResponse, RiskLevel\n')
    f.write('        from personal_ai_secretary.tools.builtin import default_tool_registry\n')
    f.write('        from uuid import uuid4\n\n')
    f.write('        registry = default_tool_registry()\n\n')
    f.write('        async def generate(request: object) -> ProviderResponse:\n')
    f.write('            return ProviderResponse(text="```tool\\n{\\"tool\\": \\"execute_command\\", \\"args\\": {\\"command\\": \\"echo hello\\"}}\\n```", provider="mock")\n\n')
    f.write('        provider = AsyncMock()\n')
    f.write('        provider.name = "mock"\n')
    f.write('        provider.model = "test-model"\n')
    f.write('        provider.generate = generate\n\n')
    f.write('        agent = ExecutionAgent(provider=provider, registry=registry)\n')
    f.write('        data = AgentInput(request_id=uuid4(), session_id=uuid4(), user_id="test", text="run echo", correlation_id="test", risk_level=RiskLevel.LOW, context={})\n')
    f.write('        result = await agent.run(data)\n')
    f.write('        assert result.content.startswith(APPROVAL_REQUIRED_PREFIX)\n')
    f.write('        assert "execute_command" in result.content\n\n')
    f.write('    @pytest.mark.asyncio\n')
    f.write('    async def test_command_metrics(self) -> None:\n')
    f.write('        from personal_ai_secretary.agents.builtin import ExecutionAgent\n')
    f.write('        from personal_ai_secretary.agents.contracts import AgentInput\n')
    f.write('        from personal_ai_secretary.domain.contracts import ProviderResponse, RiskLevel\n')
    f.write('        from personal_ai_secretary.tools.builtin import default_tool_registry\n')
    f.write('        from uuid import uuid4\n\n')
    f.write('        registry = default_tool_registry()\n\n')
    f.write('        async def generate(request: object) -> ProviderResponse:\n')
    f.write('            return ProviderResponse(text="```tool\\n{\\"tool\\": \\"execute_command\\", \\"args\\": {\\"command\\": \\"python -c \\\\\\"print(1)\\\\\\"\\\\"}}\\n```", provider="mock")\n\n')
    f.write('        provider = AsyncMock()\n')
    f.write('        provider.name = "mock"\n')
    f.write('        provider.model = "test-model"\n')
    f.write('        provider.generate = generate\n\n')
    f.write('        agent = ExecutionAgent(provider=provider, registry=registry)\n')
    f.write('        data = AgentInput(request_id=uuid4(), session_id=uuid4(), user_id="test", text="run", correlation_id="test", risk_level=RiskLevel.LOW, context={"approval_granted": True})\n')
    f.write('        await agent.run(data)\n')
    f.write('        metrics = agent.last_metrics\n')
    f.write('        assert metrics is not None\n')
    f.write('        assert metrics.command_count >= 1\n\n')

print("Written test file")
